# Generated by Django 4.2.2 on 2023-07-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('mod_date', models.DateTimeField(blank=True, null=True)),
                ('definition', models.CharField(blank=True, max_length=500, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('advertiser', models.CharField(blank=True, max_length=45, null=True)),
                ('click_cnt', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('content_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'AD_Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaTypeInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Media_Type_Info',
                'managed': False,
            },
        ),
    ]
